### ISSUE TITLE
Adding Pictures To the Manual

### ISSUE THREAD

**Issue by ReymondAkpanya** [markusbaumeister/simplicial-surfaces#121]
I tried to change the manual in the branch 'addpictures' by adding some lines to the end of ./gap/Flags/flags.gd and adding the file 'try.tex' to ./doc but executing make in the mainfolder to generate the manual does not compute the corresponding picture and gives an error

**Comment by markusbaumeister** [comment]
Looking at the first error in the log shows errors of the form
`l.1 \documentclass{article}
! LaTeX Error: Can be used only in preamble.`
These arise because try.tex is a fully compilable document. However, the SimplicialSurfaces-package uses a common header for all generated images, namely doc/TikZHeader. Since the document-class is dependent on the desired output (both svg and pdf are supported), it is set in makedoc.g

Since you appear to have created the file with DrawSurfaceToTikZ, you can create such a desired stump by using the output option "onlyTikzpicture:=true".

In general, I recommend using the prefix "Image_" for custom images, since these are automatically recognised by the Makefile.
